name: Deploy Microservices Backend
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Access Oracle server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export PATH=$PATH:/usr/local/bin/:/home/ubuntu/.nvm/versions/node/v18.19.1/bin/
            cd bookstore-backend-nodejs
            git pull 
            pm2 restart 0
            pm2 restart 1
            pm2 restart 2
            pm2 restart 3